# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pipeline.xdc

# IP: ip/single_data_mem/single_data_mem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==single_data_mem || ORIG_REF_NAME==single_data_mem} -quiet] -quiet

# IP: ip/single_text_mem/single_text_mem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==single_text_mem || ORIG_REF_NAME==single_text_mem} -quiet] -quiet

# XDC: ip/single_data_mem/single_data_mem_ooc.xdc

# XDC: ip/single_text_mem/single_text_mem_ooc.xdc
